"""Run a scenario and print its revenue summary.

The implementation is in ``bess_stack.cli``, not here. ``[tool.hatch.build.targets.wheel]``
packages only ``src/bess_stack``, so ``scripts/`` is absent from the wheel and a
``[project.scripts]`` entry point cannot target this file. Keeping the logic in the
package means the installed ``bess-stack-run`` command and this file are the same code
rather than two that drift.

This file exists so the command works from a checkout without a reinstall -- console
scripts are generated by the installer, so ``.venv/bin/bess-stack-run`` appears only
after ``pip install -e ".[dev]"`` is re-run -- and so the house
``.venv/bin/python scripts/...`` invocation covers every entry point:

    .venv/bin/python scripts/run_scenario.py scenarios/reference.yaml            # ~81 s
    .venv/bin/python scripts/run_scenario.py scenarios/reference.yaml --days 7   # ~2 s
"""

from __future__ import annotations

import sys

from bess_stack.cli import main

if __name__ == "__main__":
    sys.exit(main())
